# Site settings
title: Zhipeng DU
email:
baseurl: ""
url: "http://ZPDu.github.io"
blogurl: "http://ZPDu.github.io/blog"
github_username:  ZPDu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
